services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: dmx-mosquitto
    restart: always
    hostname: mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 8883:8883

  backend:
    image: ghcr.io/korbiniankuhn/pidmxcontrol/frontend:1.0.0
    container_name: dmx-backend
    restart: always
    environment:
      - SEND_DATA=true
      - UART_SERIAL=true
      - MQTT_HOST=mqtt://mosquitto:1883
      - STATIC_DIRECTORY=/usr/src/app/static
    volumes:
      - ./static:/usr/src/app/static
    depends_on:
      - mosquitto
    ports:
      - 3000:3000

  frontend:
    image: ghcr.io/korbiniankuhn/pidmxcontrol/frontend:1.0.0
    container_name: dmx-frontend
    restart: always
    environment:
      - BASE_REST_API=http://dmx.local:3000
      - MQTT_WS_URL=ws://dmx.local:8883
    ports:
      - 80:80
