version: "3.8"
services:
  nginx:
    restart: always
    image: nginx:alpine
    container_name: dmx-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/static:ro
    links:
      - frontend
      - backend
    ports:
      - 80:80
      - 3000:3000

  frontend:
    restart: always
    build:
      context: ./frontend
    container_name: dmx-frontend
    # ports:
    #   - 4200:80

  backend:
    restart: always
    build:
      context: ./backend
    container_name: dmx-backend
    environment:
      - CONFIG=sender
    volumes:
      - ./static:/usr/src/app/static
