version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: dmx-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - frontend
      - backend
    ports:
      - 80:80
      - 3000:3000

  frontend:
    build:
      context: ./frontend
    container_name: dmx-frontend
    # ports:
    #   - 4200:80

  backend:
    build:
      context: ./backend
    container_name: dmx-backend
    environment:
      - CONFIG=pi
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    # ports:
    #   - 3000:3000
